export enum Occupation {
  CAMP_LEADER = "CAMP_LEADER",
  WEEK_LEADER = "WEEK_LEADER",
  DOCTOR = "DOCTOR",
  PSYCHOLOGIST = "PSYCHOLOGIST",
  TEACHER = "TEACHER",
  ENGLISH_TEACHER = "ENGLISH_TEACHER",
  SMALL_TEACHER = "SMALL_TEACHER",
  SQUIRREL = "SQUIRREL",
  SMALL_SQUIRREL = "SMALL_SQUIRREL",
  BUFE = "BUFE",
  GUEST = "GUEST",
  CAMPER = "CAMPER"
}
